#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: {{ include "access-control-sso.fullname" . }}
#  labels:
#    {{- include "access-control-sso.labels" . | nindent 4 }}
#spec:
#  {{- if not .Values.autoscaling.enabled }}
#  replicas: {{ .Values.replicaCount }}
#  {{- end }}
#  selector:
#    matchLabels:
#      {{- include "access-control-sso.selectorLabels" . | nindent 6 }}
#  template:
#    metadata:
#      {{- with .Values.podAnnotations }}
#      annotations:
#        {{- toYaml . | nindent 8 }}
#      {{- end }}
#      labels:
#        {{- include "access-control-sso.labels" . | nindent 8 }}
#        {{- with .Values.podLabels }}
#        {{- toYaml . | nindent 8 }}
#        {{- end }}
#    spec:
#      {{- with .Values.imagePullSecrets }}
#      imagePullSecrets:
#        {{- toYaml . | nindent 8 }}
#      {{- end }}
#      serviceAccountName: {{ include "access-control-sso.serviceAccountName" . }}
#      {{- with .Values.podSecurityContext }}
#      securityContext:
#        {{- toYaml . | nindent 8 }}
#      {{- end }}
#      containers:
#        - name: {{ .Chart.Name }}
#          {{- with .Values.securityContext }}
#          securityContext:
#            {{- toYaml . | nindent 12 }}
#          {{- end }}
#          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
#          imagePullPolicy: {{ .Values.image.pullPolicy }}
#          ports:
#            - name: http
#              containerPort: {{ .Values.service.port }}
#              protocol: TCP
#          {{- with .Values.livenessProbe }}
#          livenessProbe:
#            {{- toYaml . | nindent 12 }}
#          {{- end }}
#          {{- with .Values.readinessProbe }}
#          readinessProbe:
#            {{- toYaml . | nindent 12 }}
#          {{- end }}
#          {{- with .Values.resources }}
#          resources:
#            {{- toYaml . | nindent 12 }}
#          {{- end }}
#          {{- with .Values.volumeMounts }}
#          volumeMounts:
#            {{- toYaml . | nindent 12 }}
#          {{- end }}
#      {{- with .Values.volumes }}
#      volumes:
#        {{- toYaml . | nindent 8 }}
#      {{- end }}
#      {{- with .Values.nodeSelector }}
#      nodeSelector:
#        {{- toYaml . | nindent 8 }}
#      {{- end }}
#      {{- with .Values.affinity }}
#      affinity:
#        {{- toYaml . | nindent 8 }}
#      {{- end }}
#      {{- with .Values.tolerations }}
#      tolerations:
#        {{- toYaml . | nindent 8 }}
#      {{- end }}

#---
# This is deployment of PostgreSQL with an ephemeral storage for testing: Once the Pod stops, the data is lost.
# For a production setup, replace it with a database setup that persists your data.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: mirror.gcr.io/postgres:17
          env:
            - name: POSTGRES_USER
              value: "keycloak"
            - name: POSTGRES_PASSWORD
              value: "keycloak"
            - name: POSTGRES_DB
              value: "keycloak"
            - name: POSTGRES_LOG_STATEMENT
              value: "all"
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            # Using volume mount for PostgreSQL's data folder as it is otherwise not writable
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
