apiVersion: v2
name: web-reactive-frontend
version: 1.0.0  # SemVer 2 version
# @Requirement(reqType = RequirementCategory.Maintainability, reqId = "REQ_MAIN_1")
description: CYBNITY user interfaces server exposing front end visual interfaces.

type: application

sources:
  # URLs to source code for the project
  - https://github.com/cybnity/iac-helm-charts/tree/main/cybnity-platform/charts/web-reactive-frontend

appVersion: "1.0.0" # Version of the app that this project contains
