# Application exposed using a CRD for exposure of all path supported by Keycloak via default ingress paths exposed by access-control-sso application module
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "access-control-sso-system-routes"
  annotations:
    "helm.sh/hook": "post-install" # Execute this resource creation after all other resources loaded into K8S (doc at https://helm.sh/docs/topics/charts_hooks/#the-available-hooks) for allow endpoint found
spec:
  entryPoints:
    - web
  routes:
    # Define path set required to be exposed for Keycloak interactions (see https://www.keycloak.org/server/reverseproxy)
    - match: Host(`dev-deploy.cybnity.tech`)
      kind: Rule
      services:
        - name: "access-control-sso-system"
          port: 8080 # Keycloak http main service entrypoint
