apiVersion: v1
kind: Service
metadata:
  name: {{ include "access-control-sso.fullname" . }}
  labels:
    {{- include "access-control-sso.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "access-control-sso.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "access-control-sso.labels" . | nindent 4 }}
  name: {{ .Values.statefull.serviceName }}
spec:
  selector:
    {{- include "access-control-sso.selectorLabels" . | nindent 4 }}
  clusterIP: None
  type: {{ .Values.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.postgre.serviceName }}
  name: {{ .Values.postgre.serviceName }}
spec:
  selector:
    app: {{ .Values.postgre.serviceName }}
  ports:
    - protocol: {{ .Values.postgre.protocol }}
      port: {{ .Values.postgre.port }}
      targetPort: {{ .Values.postgre.targetPort }}
  type: {{ .Values.postgre.type }}
